# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUI_create.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DLG_Create(object):
    def setupUi(self, DLG_Create):
        DLG_Create.setObjectName("DLG_Create")
        DLG_Create.resize(570, 70)
        self.BTNBOX = QtWidgets.QDialogButtonBox(DLG_Create)
        self.BTNBOX.setGeometry(QtCore.QRect(440, 0, 121, 71))
        self.BTNBOX.setOrientation(QtCore.Qt.Vertical)
        self.BTNBOX.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Save)
        self.BTNBOX.setCenterButtons(True)
        self.BTNBOX.setObjectName("BTNBOX")
        self.LBL = QtWidgets.QLabel(DLG_Create)
        self.LBL.setGeometry(QtCore.QRect(10, 10, 161, 21))
        self.LBL.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LBL.setObjectName("LBL")
        self.LNEdit_PN = QtWidgets.QLineEdit(DLG_Create)
        self.LNEdit_PN.setGeometry(QtCore.QRect(180, 10, 251, 20))
        self.LNEdit_PN.setObjectName("LNEdit_PN")
        self.LBL_4 = QtWidgets.QLabel(DLG_Create)
        self.LBL_4.setGeometry(QtCore.QRect(10, 40, 161, 21))
        self.LBL_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.LBL_4.setObjectName("LBL_4")
        self.LNEdit_NSF = QtWidgets.QLineEdit(DLG_Create)
        self.LNEdit_NSF.setGeometry(QtCore.QRect(180, 40, 251, 20))
        self.LNEdit_NSF.setReadOnly(False)
        self.LNEdit_NSF.setObjectName("LNEdit_NSF")

        self.retranslateUi(DLG_Create)
        self.BTNBOX.accepted.connect(DLG_Create.accept) # type: ignore
        self.BTNBOX.rejected.connect(DLG_Create.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(DLG_Create)

    def retranslateUi(self, DLG_Create):
        _translate = QtCore.QCoreApplication.translate
        DLG_Create.setWindowTitle(_translate("DLG_Create", "PZ-CMF_Create"))
        self.LBL.setText(_translate("DLG_Create", "Profile name:"))
        self.LBL_4.setText(_translate("DLG_Create", "Name folder with save:"))
